(() => {
'use strict';
const E=window.FOOD_PICKER_ENGINE,M=Array.isArray(window.FOODS)?window.FOODS:(typeof FOODS!=='undefined'&&Array.isArray(FOODS)?FOODS:[]),$=id=>document.getElementById(id),MAXH=12;
const screens={intro:$('intro'),quiz:$('quiz'),loading:$('loading'),result:$('result')};
const dom={start:$('startBtn'),resume:$('resumeBtn'),retest:$('retestBtn'),saved:$('savedProfile'),savedTitle:$('savedTitle'),step:$('qStep'),prog:$('prog'),text:$('qText'),choices:$('choices'),back:$('quizBackBtn'),loading:$('loadingLine'),modal:$('shareModal'),status:$('shareStatus'),preview:$('sharePreview'),share:$('shareFileBtn'),download:$('downloadBtn'),copy:$('copyLinkBtn'),close:$('closeShareBtn')};
const COPY={
'close-the-day':['忙活一天，总算歇了。哪一下最像：得，今儿就到这儿？',['门一关，出去溜达一圈','洗个热水澡，先缓会儿','把最后那点尾巴顺手扫了','屋里开点动静，别那么空']],
'stalled-room':['几个人聊半天，还是没聊出个所以然。你先来哪句？',['先甭管了，随便定一个再说','先看看，到底卡哪儿了','所以你们到底想说啥？','要不换个说法呗']],
'friend-response':['你今儿看着不太对劲儿，朋友也看出来了。哪句最管用？',['你是不是就憋着这事儿呢？','行，我不问了，坐会儿吧','得，这事儿我来','先聊点别的吧']],
'weekend-memory':['想起一个过得挺舒坦的周末，你先想起啥？',['有一下特对：哎，今儿值了','没啥大事，反正一整天都挺顺','有个小事儿，想起来还挺乐','说不上来，反正感觉对了']],
'inhabited-room':['一个地方住久了，哪一下会让你觉得：嗯，这儿算我的了？',['这东西就得在这儿，挪哪儿都不对','什么东西都得有自己的地儿','光线、声音、屋里那股味儿都对了','有个地方能一屁股窝进去']],
'calibrate-heat':['白捡一个下午，你准备怎么混过去？',['出门，去个没去过的地儿','不安排，溜达到哪儿算哪儿','把一直碍眼的破事儿顺手清了','就在熟悉的街边晃悠晃悠']],
'calibrate-texture':['有人发来半截话，看得人云里雾里。你更想回哪句？',['那你到底想说啥？','先放着吧，他想说再说','你意思是这个，对吧？','先说你怎么了，别的回头再聊']],
'calibrate-focus':['一件事折腾老半天，总算完了。哪一下最痛快？',['最后一下卡上了，咔，齐活','那堆零碎终于都顺了','有人说：最难那块你真弄明白了','第二天起来，这事儿已经翻篇了']],
'calibrate-meaning':['用了好多年的东西坏了。你第一反应怎么弄？',['照原样修，别瞎改','拆了，能用的改点别的','留块最有念想的，别的算了','重新做一个现在顺手的']],
'world-request':['接下来的两个小时，你最希望世界对你做什么？',['别让我选了，真的','想爽一把，把人叫醒','好歹给今天收个像样的尾','闹点动静，别太安静']],
'bandwidth':['今晚这顿，你还愿意费多少心思？',['一步到位，别折腾','稍微费点事也成','今儿还有精神，认真弄弄','咋都行，别太麻烦']]
};
const EXTRA=[
['plan-cancelled','本来约好出门，临了对方来一句：今儿算了吧。你第一反应？',[['↗','那我自己出去溜达',{heat:2,focus:1}],['≈','那正好，躺会儿',{heat:-2,texture:-1}],['?','咋了？出啥事儿了？',{texture:2,meaning:1}],['↺','行，那改天换个玩法',{meaning:-2,focus:-1}]]],
['movie-talk','一部电影看完了，跟人聊起来你最容易先说哪句？',[['✦','就那个镜头，真行',{focus:2,heat:1}],['—','整体挺顺，没哪儿特别掉链子',{focus:-2,heat:-1}],['◌','那个人演得真像那么回事儿',{meaning:2,texture:1}],['∞','我就喜欢它把几件破事儿串到一块儿',{meaning:-2,focus:-1}]]],
['wrong-turn','出去玩走错路了，多绕二十分钟。你一般咋想？',[['↗','来都来了，顺路看看呗',{heat:2,meaning:-1}],['!','先把路找回来，别越走越偏',{texture:2,focus:1}],['≈','没事儿，慢慢走，反正也不赶',{heat:-2,texture:-1}],['⌁','记住这破岔路，下回别再走岔了',{meaning:2,focus:1}]]],
['gift-stays','别人送你个东西，哪种最容易一直留着？',[['●','正好就是我缺的那个',{focus:2,meaning:1}],['⌁','不值钱，但他真知道我啥脾气',{meaning:2,texture:1}],['✦','包装、卡片、那点小心思全在点儿上',{meaning:-2,focus:1}],['○','说不上哪儿好，反正舍不得扔',{focus:-2,texture:-1}]]],
['change-place','一群人临时说换地方，你最容易回哪句？',[['→','走呗，换',{heat:2,focus:1}],['?','等等，先说去哪儿',{texture:2,meaning:1}],['…','都行，别来回折腾就成',{heat:-2,texture:-1}],['↺','那干脆换个事儿干呗',{meaning:-2,focus:-1}]]],
['halfway-wrong','一件事做到一半，突然发现原来那招不太行。你咋办？',[['↗','先改呗，能接着弄就行',{heat:2,focus:1}],['!','停一下，先看看哪儿不对',{texture:2,meaning:1}],['●','保住最要紧那块，别全推倒',{focus:2,meaning:1}],['↺','那就重来，旧的别硬救',{meaning:-2,heat:1}]]],
['rain-plan','本来安排得好好的，突然下大雨。你更像哪种？',[['↗','换个地方，照样出去',{heat:2,meaning:-1}],['≈','得，回家窝着也挺好',{heat:-2,texture:-1}],['!','先看看雨多大，别瞎折腾',{texture:2,meaning:1}],['⌘','那就临时整点别的',{meaning:-2,focus:-1}]]]
].map(([id,text,opts])=>({id,text,hint:'',options:opts.map(([icon,title,axis])=>({icon,title,sub:'',axis}))}));
const DAILY=[
['room-noise','现在屋里要开点声音，你想开到哪档？',[['○','安静点儿，谁也别找我',{comfort:4,easy:3,familiar:2}],['♬','随便开点东西，别太空',{comfort:2,social:2,familiar:2}],['!','来点带劲的，醒醒',{stimulus:5,spicy:2,crisp:1}],['◉','最好来个人，坐一桌',{social:5,shareable:4,comfort:1}]]],
['day-tail','今天要是现在就翻篇，你想留个啥尾巴？',[['—','啥也别留，赶紧过去',{easy:5,comfort:3,familiar:1}],['!','来点爽的，别白熬一天',{reward:4,stimulus:3,spicy:2}],['✦','有个小惊喜就行',{novel:4,reward:3,ritual:2}],['♬','跟人说两句，别闷着',{social:5,shareable:3}]]],
['inside-weather','你现在这人，大概啥天气？',[['☁','蔫了，别折腾',{comfort:5,easy:4}],['↗','闷得慌，得来点风',{light:3,fresh:3,novel:2}],['!','有点炸，想来点更狠的',{stimulus:5,spicy:4}],['◉','还行，想热闹热闹',{social:4,reward:2,shareable:3}]]]
].map(([id,text,opts])=>({id,text,hint:'',options:opts.map(([icon,title,mood])=>({icon,title,sub:'',mood}))}));
const DAILY_IDS=new Set([...E.DAILY_QUESTIONS.map(q=>q.id),...DAILY.map(q=>q.id)]);
let mode='full',queue=[],profileSet=[],dailySet=[],answers=[],step=0,base=null,profile=null,daily=null,fortune=null,ranked=[],rankIndex=0,shareAsset=null,shareBusy=false;
function applyCopy(){[...E.PROFILE_QUESTIONS,...Object.values(E.CALIBRATORS),...E.DAILY_QUESTIONS].forEach(q=>{const c=COPY[q.id];if(!c)return;q.text=c[0];q.hint='';c[1].forEach((t,i)=>{if(q.options[i]){q.options[i].title=t;q.options[i].sub='';}});});}
function shuffle(a){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function coverage(q){const s=new Set();q.options.forEach(o=>Object.keys(o.axis||{}).forEach(k=>s.add(k)));return s;}
function pickProfile(){const pool=[...E.PROFILE_QUESTIONS,...EXTRA];for(let n=0;n<60;n++){const p=shuffle(pool).slice(0,5),c=Object.fromEntries(E.AXES.map(a=>[a.key,0]));p.forEach(q=>coverage(q).forEach(k=>c[k]++));if(E.AXES.every(a=>c[a.key]>=2))return p;}return E.PROFILE_QUESTIONS.slice(0,5);}
function pickDaily(){const w=E.DAILY_QUESTIONS.find(q=>q.id==='world-request'),b=E.DAILY_QUESTIONS.find(q=>q.id==='bandwidth'),p=[w,...DAILY].filter(Boolean);return [p[Math.floor(Math.random()*p.length)]||w,b].filter(Boolean);}
function parse(v,f=null){try{return JSON.parse(v)}catch{return f}}function get(k,f=null){try{return parse(localStorage.getItem(k),f)}catch{return f}}function set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}function del(k){try{localStorage.removeItem(k)}catch{}}
function saved(){const x=get(E.PROFILE_STORAGE_KEY);return x&&x.version===E.VERSION&&E.archetypeById(x.archetypeId)&&E.AXES.every(a=>Number.isFinite(x.values?.[a.key]))?x:null;}
function history(){const h=get(E.HISTORY_STORAGE_KEY,[]);return Array.isArray(h)?h.filter(Boolean).slice(0,MAXH):[]}function addHistory(n){set(E.HISTORY_STORAGE_KEY,[n,...history().filter(x=>x!==n)].slice(0,MAXH));}
function show(target){Object.values(screens).forEach(s=>s?.classList.toggle('hidden',s!==target));scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}function toast(t){const n=$('toast');if(!n)return;n.textContent=t;n.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('on'),1800);}
function today(){const d=new Date;return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}function decorate(p,d,seed){const a=E.archetypeById(p.archetypeId),word=E.chooseFloatWord(a,d,seed);return {...p,archetype:a,word,title:`${a.pot}${word}${a.role}`};}
function renderSaved(){const s=saved(),has=!!s;dom.saved?.classList.toggle('hidden',!has);dom.start?.classList.toggle('hidden',has);dom.resume?.classList.toggle('hidden',!has);dom.retest?.classList.toggle('hidden',!has);if(has){const a=E.archetypeById(s.archetypeId);if(dom.savedTitle)dom.savedTitle.textContent=`${a.pot}${a.defaultWord}${a.role}`;}}
function startFull(){mode='full';base=profile=null;profileSet=pickProfile();dailySet=pickDaily();queue=profileSet.slice();answers=[];step=0;show(screens.quiz);renderQuestion();}function startDaily(){base=saved();if(!base)return startFull();mode='daily';profile=null;dailySet=pickDaily();queue=dailySet.slice();answers=[];step=0;show(screens.quiz);renderQuestion();}
function total(){return mode==='full'?8:2}function renderQuestion(){const q=queue[step];if(!q)return calculate();dom.step.textContent=mode==='full'?`第 ${step+1} 题 / ${total()}`:`今天 ${step+1} / ${total()}`;dom.prog.style.width=`${(step+1)/total()*100}%`;dom.text.textContent=q.text;dom.choices.innerHTML='';dom.back.disabled=step===0;q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='choice';b.type='button';b.innerHTML=`<span class="ico">${o.icon}</span><span><b></b></span>`;b.querySelector('b').textContent=o.title;b.onclick=()=>choose(i);dom.choices.appendChild(b);});}
function choose(i){const q=queue[step],o=q?.options[i];if(!o)return;answers.push({questionId:q.id,kind:DAILY_IDS.has(q.id)?'daily':'profile',option:o});if(mode==='full'&&step===profileSet.length-1){const ps=answers.filter(x=>x.kind==='profile').map(x=>x.option);queue=[...profileSet,E.getCalibrationQuestion(ps),...dailySet];}step++;step>=queue.length?calculate():renderQuestion();}function back(){if(step<=0)return;step--;answers.pop();if(mode==='full'&&step<profileSet.length)queue=profileSet.slice();renderQuestion();}
const LOAD=['看看哪道菜最会来事。','刚才那些答案，正在偷偷往厨房里拐。','有几道菜挤得挺靠前。','快了，别让它算半天。'];
function calculate(){if(!E||!M.length)return toast('这口锅今天没点着');show(screens.loading);let i=0;dom.loading.textContent=LOAD[0];const timer=setInterval(()=>dom.loading.textContent=LOAD[++i%LOAD.length],420),pa=answers.filter(x=>x.kind==='profile').map(x=>x.option),da=answers.filter(x=>x.kind==='daily').map(x=>x.option);if(mode==='full'){base=E.buildProfile(pa,`${today()}:${pa.map(x=>x.title).join('|')}`);set(E.PROFILE_STORAGE_KEY,base);}daily=E.buildDaily(da);const seed=`${today()}:${base.archetypeId}:${daily.selections.join('|')}`;profile=decorate(base,daily,seed);fortune=E.fortuneFor(`${seed}:${new Date().getHours()}`);ranked=E.weightedDraw(E.rankMeals(M,profile,daily,{}, {seed,fortune,history:history()}),Math.min(8,M.length),seed);rankIndex=0;setTimeout(()=>{clearInterval(timer);if(!ranked.length){show(screens.intro);return toast('菜单没接上，刷新一下再来')}renderResult();renderSaved();},720);}
function current(){return ranked[rankIndex%ranked.length]||null}function verdict(meal){const v=profile.values,first=v.heat>=0?'今儿别老温吞着，来点动静':'今儿已经够吵了，后面慢一点';let second=v.texture>=0?'吃着也得有点嚼头':'吃着顺口点，别再费劲';if((daily.mood.easy||0)>=4)second='这顿最好省点事';else if((daily.mood.reward||0)>=4)second='好歹给今天收个正经尾';else if((daily.mood.social||0)>=4)second='最好再来点人气';else if((daily.mood.light||0)>=4)second='这会儿别吃太顶的';else if((daily.mood.stimulus||0)>=4)second='再来点带劲的';return `${first}，${second}。就吃${meal.name}。`;}
function fitMeal(){const n=$('mealName');if(!n)return;n.classList.remove('meal-two-lines');n.style.fontSize='';let s=46;while(n.scrollWidth>n.clientWidth&&s>30){s-=2;n.style.fontSize=`${s}px`;}if(n.scrollWidth>n.clientWidth){n.style.fontSize='';n.classList.add('meal-two-lines');}}
function renderResult(){const meal=current();if(!meal)return;show(screens.result);$('personaTitle').textContent=profile.title;$('mealName').textContent=meal.name;$('mealNative').textContent=meal.native||'';$('psychVerdict').textContent=verdict(meal);$('crossList').innerHTML=meal.cross.slice(0,3).map(x=>`<div class="cross-item"><b>${x.title}</b></div>`).join('');$('altList').innerHTML=ranked.filter(x=>x.name!==meal.name).slice(0,3).map(x=>`<button class="alt" type="button" data-name="${x.name.replace(/"/g,'&quot;')}">${x.name}</button>`).join('');document.querySelectorAll('#altList .alt').forEach(b=>b.onclick=()=>{const i=ranked.findIndex(x=>x.name===b.dataset.name);if(i>=0){rankIndex=i;renderResult();}});requestAnimationFrame(fitMeal);}
function reroll(){if(!ranked.length)return;rankIndex=(rankIndex+1)%Math.min(6,ranked.length);renderResult();}
function rr(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();}
const FONT='"PingFang SC","Microsoft YaHei","Noto Sans CJK SC",sans-serif',PLAY='"Xingkai SC","STXingkai","Hannotate SC","HanziPen SC","Wawati SC","Weibei SC","Songti SC",serif',FALL='https://github.com/StarObserverPro/FoodPicker';function font(c,w,s,f=FONT){c.font=`${w} ${s}px ${f}`;}function wrap(c,t,w){const out=[];let line='';for(const ch of String(t)){if(line&&c.measureText(line+ch).width>w){out.push(line);line=ch}else line+=ch}if(line)out.push(line);return out;}
function drawFit(c,t,x,y,w,{max=2,size=72,min=38,weight=800,family=FONT,ratio=1.18}={}){let lines;for(;size>=min;size-=2){font(c,weight,size,family);lines=wrap(c,t,w);if(lines.length<=max)break}lines=(lines||['']).slice(0,max);font(c,weight,size,family);lines.forEach((l,i)=>c.fillText(l,x,y+i*Math.round(size*ratio)));return y+(lines.length-1)*Math.round(size*ratio);}
function pageUrl(){if(location.origin&&location.origin!=='null'){const u=new URL(location.pathname||'/',location.origin);u.search='';u.hash='';return u.toString()}return FALL}function shareUrl(meal){const origin=location.origin&&location.origin!=='null'?location.origin:'';return E.makeShareUrl(meal,profile.title,{origin,pathname:location.pathname||'/'});}function qrUrl(){const max=window.FoodPickerQR?.maxBytes||106,enc=s=>typeof TextEncoder==='function'?new TextEncoder().encode(s).length:s.length;for(const s of [pageUrl(),FALL])if(enc(s)<=max)return s;return FALL;}
function card(meal){if(!window.FoodPickerQR)throw Error('QR');const cv=document.createElement('canvas');cv.width=1080;cv.height=1440;const c=cv.getContext('2d');c.fillStyle='#f1e5d3';c.fillRect(0,0,1080,1440);c.fillStyle='#fffaf0';rr(c,58,54,964,1332,44);c.fill();c.fillStyle='#2f2923';const tb=drawFit(c,profile.title,104,166,872,{size:78,min:50,weight:700,family:PLAY});c.fillStyle='#d94d3f';const mb=drawFit(c,meal.name,104,Math.max(352,tb+78),872,{size:100,min:64,weight:900});const top=Math.min(680,Math.max(540,mb+62));c.fillStyle='#332c26';rr(c,96,top,888,224,28);c.fill();c.fillStyle='#fff8e9';drawFit(c,verdict(meal),138,top+78,804,{max:2,size:38,min:30,weight:700,ratio:1.38});c.fillStyle='#fff';rr(c,710,1052,266,266,26);c.fill();try{window.FoodPickerQR.paint(c,qrUrl(),728,1070,230,{dark:'#2f2923',light:'#fff',quiet:4})}catch{window.FoodPickerQR.paint(c,FALL,728,1070,230,{dark:'#2f2923',light:'#fff',quiet:4})}c.fillStyle='#2f2923';font(c,700,34,PLAY);c.fillText('扫码，你也来一口',104,1138);c.fillStyle='#7c6f62';font(c,600,24);c.fillText('先吃饭，别研究了。',104,1196);return cv;}
function toBlob(cv){return new Promise((ok,bad)=>{if(cv.toBlob)return cv.toBlob(b=>b?ok(b):bad(Error('png')),'image/png');try{const d=cv.toDataURL('image/png'),bin=atob(d.split(',')[1]),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);ok(new Blob([a],{type:'image/png'}))}catch(e){bad(e)}})}function openModal(){dom.modal?.classList.remove('hidden');document.body.classList.add('share-open')}function closeModal(){dom.modal?.classList.add('hidden');document.body.classList.remove('share-open')}
async function makeShare(){const meal=current();if(!meal||shareBusy)return;shareBusy=true;$('shareModalTitle').textContent=`${profile.title} · ${meal.name}`;openModal();dom.status.textContent='正画呢，稍等……';dom.status.classList.remove('hidden');dom.preview.removeAttribute('src');dom.share.disabled=dom.download.disabled=true;try{if(document.fonts?.ready)await document.fonts.ready;const cv=card(meal),blob=await toBlob(cv),url=URL.createObjectURL?URL.createObjectURL(blob):cv.toDataURL('image/png'),fileName=`今天吃什么-${profile.title}-${meal.name}.png`.replace(/[\\/:*?"<>|]/g,'-'),file=typeof File==='function'?new File([blob],fileName,{type:'image/png'}):null;if(shareAsset?.url?.startsWith('blob:')&&URL.revokeObjectURL)URL.revokeObjectURL(shareAsset.url);shareAsset={blob,url,file,fileName,meal,shareUrl:shareUrl(meal)};dom.preview.src=url;dom.status.classList.add('hidden');dom.share.disabled=dom.download.disabled=false}catch(e){console.error(e);dom.status.textContent='刚才没画成，再点一次试试。';toast('刚才没画成，再来一下')}finally{shareBusy=false}}
async function acceptShare(){const meal=current();if(!meal)return;addHistory(meal.name);await makeShare()}function download(){if(!shareAsset)return;const a=document.createElement('a');a.href=shareAsset.url;a.download=shareAsset.fileName;document.body.appendChild(a);a.click();a.remove()}async function share(){if(!shareAsset)return;try{const can=shareAsset.file&&navigator.share&&(!navigator.canShare||navigator.canShare({files:[shareAsset.file]}));if(can)await navigator.share({files:[shareAsset.file],title:`${profile.title} · 今天吃${shareAsset.meal.name}`,text:`今儿就吃${shareAsset.meal.name}。`});else if(navigator.share)await navigator.share({title:`${profile.title} · 今天吃${shareAsset.meal.name}`,text:`今儿就吃${shareAsset.meal.name}。`,url:shareAsset.shareUrl});else{download();toast('图先存下来了')}}catch(e){if(e?.name!=='AbortError')toast('没发出去，先存图吧')}}
async function copy(t){try{await navigator.clipboard.writeText(t)}catch{}toast('链接抄好了')}function shared(){const p=new URLSearchParams(location.search);if(!['share','share-card'].includes(p.get('from')))return;const meal=(p.get('meal')||'').slice(0,60),persona=(p.get('persona')||p.get('type')||'').slice(0,40),n=$('sharedInvite');if(!n||(!meal&&!persona))return;n.textContent=meal&&persona?`有人测出「${persona}」，今天落到「${meal}」。你也来一口？`:`有人把「${meal||persona}」端过来了。你也来一锅？`;n.classList.remove('hidden');}
function reset(){del(E.PROFILE_STORAGE_KEY);closeModal();renderSaved();startFull()}function wire(){dom.start?.addEventListener('click',startFull);dom.resume?.addEventListener('click',startDaily);dom.retest?.addEventListener('click',startFull);dom.back?.addEventListener('click',back);$('acceptBtn')?.addEventListener('click',acceptShare);$('rerollBtn')?.addEventListener('click',reroll);$('resetProfileBtn')?.addEventListener('click',reset);dom.close?.addEventListener('click',closeModal);dom.share?.addEventListener('click',share);dom.download?.addEventListener('click',download);dom.copy?.addEventListener('click',()=>current()&&copy(shareUrl(current())));dom.modal?.addEventListener('click',e=>e.target===dom.modal&&closeModal());document.addEventListener('keydown',e=>e.key==='Escape'&&closeModal());}
function boot(){if(!E){dom.start.disabled=true;dom.start.textContent='这口锅今天没点着';return}applyCopy();if(!M.length){dom.start.disabled=true;dom.start.textContent='菜单没接上';if(dom.resume)dom.resume.disabled=true}renderSaved();shared();wire();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));}boot();
})();
